model:
    in_channels: 1
    down_num: 5
    t_emb: 128
    base_ch: 64
train:
    mini_batch_size: 64
    epochs: 100
    snapshot_freq_epoch: 10
    ckp_point_path: "./checkpoints"
    decoder_ckp_for_load: 100
data:
    data_store_path: 'path/to/data'
    modalities_name: ["flair.nii.gz","t1.nii.gz","t2.nii.gz"]
    modalities_target: "t1ce.nii.gz"
optim_FMM:
    weight_decay: 0.00001
    lr: 0.00001
optim_Diff:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00003
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000
    sampling_schedule: uni
Diff_train:
    snapshot_freq: 50000
    stop_step: 1500000
sampling:
    ckpt_id: null


